/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.group5.paul_esys.screens.registrar.cards;

/**
 *
 * @author nytri
 */
public class FacultyMemberCard extends javax.swing.JPanel {

	/**
	 * Creates new form FacultyMemberCard
	 */
	public FacultyMemberCard() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblFullName = new javax.swing.JLabel();
                lblEmail = new javax.swing.JLabel();
                btnUpdate = new javax.swing.JButton();

                setBackground(new java.awt.Color(255, 255, 255));

                lblFullName.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
                lblFullName.setText("Last Name, First Name");

                lblEmail.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                lblEmail.setForeground(new java.awt.Color(102, 102, 102));
                lblEmail.setText("lastname.firstname@vbsu.edu.ph");

                btnUpdate.setBackground(new java.awt.Color(119, 0, 0));
                btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
                btnUpdate.setText("Update");
                btnUpdate.addActionListener(this::btnUpdateActionPerformed);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUpdate))
                                        .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblFullName)
                                        .addComponent(btnUpdate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmail)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnUpdateActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnUpdate;
        private javax.swing.JLabel lblEmail;
        private javax.swing.JLabel lblFullName;
        // End of variables declaration//GEN-END:variables
}
