/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group5.paul_esys.screens.shared.forms;

/**
 *
 * @author nytri
 */
public class PrivacyPolicy extends javax.swing.JFrame {
	
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrivacyPolicy.class.getName());

	/**
	 * Creates new form PrivacyPolicy
	 */
	public PrivacyPolicy() {
		initComponents();
		initCustomComponents();
	}

	private void initCustomComponents() {
		setTitle("Privacy Policy - Vince Batecan State University");
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setSize(600, 700);
		setLocationRelativeTo(null);

		javax.swing.JEditorPane editorPane = new javax.swing.JEditorPane();
		editorPane.setEditable(false);
		editorPane.setContentType("text/html");

		try {
			java.net.URL url = getClass().getResource("/docs/privacy_policy.html");
			if (url != null) {
				editorPane.setPage(url);
			} else {
				editorPane.setText("<html><body><h1>Error</h1><p>Privacy Policy file not found.</p></body></html>");
			}
		} catch (java.io.IOException e) {
			editorPane.setText("<html><body><h1>Error</h1><p>Could not load Privacy Policy.</p></body></html>");
			logger.log(java.util.logging.Level.SEVERE, null, e);
		}

		javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(editorPane);
		getContentPane().setLayout(new java.awt.BorderLayout());
		getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new PrivacyPolicy().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        // End of variables declaration//GEN-END:variables
}
