package com.group5.paul_esys.screens.admin;

import com.group5.paul_esys.screens.admin.panels.AdminCurriculumManagement;
import com.group5.paul_esys.screens.admin.panels.AdminDashboardPanel;
import com.group5.paul_esys.screens.admin.panels.AdminDepartmentManagement;
import com.group5.paul_esys.screens.admin.panels.AdminRoomsManagementPanel;
import com.group5.paul_esys.screens.admin.panels.AdminSubjectManagement;
import com.group5.paul_esys.modules.admin.model.Admin;
import com.group5.paul_esys.modules.users.services.UserSession;
import com.group5.paul_esys.screens.shared.panels.SettingsPanel;
import com.group5.paul_esys.screens.sign_in.SignIn;
import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author nytri
 */
public final class AdminDashboard extends javax.swing.JFrame {

        /**
         * Creates new form AdminDashboard
         */
        public AdminDashboard() {
                this.setUndecorated(true);
                initComponents();
                configureLogoutAction();
                this.setLocationRelativeTo(null);
                this.initializeFrame();
        }

        private void configureLogoutAction() {
                JButton logoutButton = new JButton("Logout");
                logoutButton.setFont(new Font("Poppins", Font.PLAIN, 13));
                logoutButton.putClientProperty("JButton.buttonType", "roundRect");
                logoutButton.putClientProperty("JComponent.minimumWidth", 120);
                logoutButton.addActionListener(evt -> logoutCurrentUser());

                JPanel trailingPanel = new JPanel(new BorderLayout());
                trailingPanel.setOpaque(false);
                trailingPanel.setBorder(BorderFactory.createEmptyBorder(10, 8, 12, 8));
                trailingPanel.add(logoutButton, BorderLayout.SOUTH);

                tabbedPaneAdmin.putClientProperty("JTabbedPane.trailingComponent", trailingPanel);
        }

        private void logoutCurrentUser() {
                int confirm = JOptionPane.showConfirmDialog(
                                this,
                                "Are you sure you want to logout?",
                                "Confirm Logout",
                                JOptionPane.YES_NO_OPTION,
                                JOptionPane.QUESTION_MESSAGE);

                if (confirm != JOptionPane.YES_OPTION) {
                        return;
                }

                UserSession.getInstance().logout();
                this.dispose();
                SwingUtilities.invokeLater(() -> new SignIn().setVisible(true));
        }

        public void initializeFrame() {
                Admin admin = (Admin) UserSession.getInstance().getUserInformation().getUser();
                String fullName = admin.getFirstName() + " " + admin.getLastName();
                this.windowBar1.setTitle("Welcome, " + fullName);
                this.tabbedPaneAdmin.add("Users", new AdminDashboardPanel());
                this.tabbedPaneAdmin.add("Subjects", new AdminSubjectManagement());
                this.tabbedPaneAdmin.add("Curriculum", new AdminCurriculumManagement());
                this.tabbedPaneAdmin.add("Rooms", new AdminRoomsManagementPanel());
                this.tabbedPaneAdmin.add("Departments", new AdminDepartmentManagement());
                this.tabbedPaneAdmin.add("Security", new SettingsPanel());
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                rootPanel = new javax.swing.JPanel();
                tabbedPaneAdmin = new javax.swing.JTabbedPane();
                windowBar1 = new com.group5.paul_esys.components.WindowBar();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                rootPanel.setBackground(new java.awt.Color(255, 255, 255));

                tabbedPaneAdmin.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
                tabbedPaneAdmin.setTabPlacement(javax.swing.JTabbedPane.LEFT);

                javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
                rootPanel.setLayout(rootPanelLayout);
                rootPanelLayout.setHorizontalGroup(
                                rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tabbedPaneAdmin, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                1280, Short.MAX_VALUE)
                                                .addComponent(windowBar1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                rootPanelLayout.setVerticalGroup(
                                rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(rootPanelLayout.createSequentialGroup()
                                                                .addComponent(windowBar1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(tabbedPaneAdmin,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                707,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel rootPanel;
        private javax.swing.JTabbedPane tabbedPaneAdmin;
        private com.group5.paul_esys.components.WindowBar windowBar1;
        // End of variables declaration//GEN-END:variables
}
